/*
 * generated by Xtext 2.15.0
 */
package shortcutHelper.ide


/**
 * Use this class to register ide components.
 */
class ModelisationLanguageIdeModule extends AbstractModelisationLanguageIdeModule {
}
