/*
 * generated by Xtext 2.15.0
 */
package shortcutHelper


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ModelisationLanguageRuntimeModule extends AbstractModelisationLanguageRuntimeModule {
}
